services:
  - docker:20.10.16-dind

before_script:
  - docker info
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - echo "Build docker image.."
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA ./
    - echo "Success, pushing to dockerhub"
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

deploy-job:
  stage: deploy 
  environment: production
  script:
    - echo "No auto deploy setup at this time"
